### ISSUE TITLE
How to get access to :8081/visualobjects when deployed in Azure Cluster?

### ISSUE THREAD

**Issue by vyunev** [Azure-Samples/service-fabric-dotnet-getting-started#11]
Hello!

Thanks for great example! Locally works great and I able to access localhost:8081/visualobjects endpoint. Though when I trying to deploy cluster to Azure I can't find the way I could access this page. First I made LB Rule for 8081, but as web service deployed on only one of five VMs (nodes) it only available if LB choose right VM to make request.

Could you please clarify how to make right deployment and config of VisualObject example to Azure Cluster.

Thanks in advance!

**Comment by mani-ramaswamy** [comment]
Hello,

I am assuming it was successfully published to your cluster (and if your cluster is secure you have configured it appropriately  https://azure.microsoft.com/en-us/documentation/articles/service-fabric-visualstudio-configure-secure-connections/)? And you are verifying this using service fabric explorer @  http://vyunev.regionus.cloudapp.azure.com:19000/Explorer/index.html (replaced with the appropriate endpoint)?

When you setup the LB rule, I assume you followed the instructions @ https://azure.microsoft.com/en-us/documentation/articles/service-fabric-cluster-creation-via-portal/

Have you been able to publish any other app (say to port 80) to the cluster and access it?

The webservice may be running as single instance, since it is a stateless service; only the actor project is stateful and has partitions.  When accessing it at Azure, you need to provide the FQDN (Fully Qualified Domain Name), so it would be something like http://vyunev.regionus.cloudapp.azure.com:8081/visualobjects/  (replace with the appropriate endpoint)


Regards,
Mani

**Comment by serjSmor** [comment]
I have the same problem, and my cluster is unsecured. 

@vyunev any update ?

**Comment by VipulM-MSFT** [comment]
When you deploy the application to the cloud, set the instance count for the web service to be -1. See the Cloud.xml application parameter file.

**Comment by serjSmor** [comment]
Finally solved it, inside the service port config (a.k.a ServiceManifest.xml) there is a port setting. After changing it to 19080 - the default http port my cluster was listening to, everything started working.

![image](https://cloud.githubusercontent.com/assets/5365944/14484996/06a73c06-0109-11e6-9aa7-002800254778.png)

**Comment by VipulM-MSFT** [comment]
It is not recommended to reuse the cluster management endpoint port. Open port 8082 for the load balancer and use that port in the sample.
